config/routes.rb
Rails.application.routes.draw do

  post "/products/new"

  root "stores#show" 

  resources :stores
  resources :products
  resources :admins

  namespace :api do
    namespace :v1 do
      resources :products
      end
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :store
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  Product.connection
  belongs_to :store

  # def self.muestralos
  #   response = RestClient.get'192.168.34.129:3000/api/v1/products'
  #   @response = JSON.parse(response)
  #   return @response
  # end

  # def self.muestralos_2
  #   response = RestClient.get'192.168.34.229:3000/api/v1/products.json'
  #   @response = JSON.parse(response)
  #   return @response
  # end

  def self.muestralos_3
    response = RestClient.get'192.168.34.95:3000/api/v1/products'
    @response = JSON.parse(response)
    return @response
  end

  # def self.muestralos_4
  #   response = RestClient.get'192.168.34.129:3000/api/v1/products'
  #   @response = JSON.parse(response)
  #   return @response
  # end

  # def self.muestralos_5
  #   response = RestClient.get'190.79.216.148:3001/products/index'
  #   @response = JSON.parse(response)
  #   return @response
  # end

  # def server_search
  #   uri = URI.parse("http://localhost:3000/products")
  #   Net::HTTP::Get.index(uri.request_uri)request.set_form_data({"product[name]"})

  #   response = http.request(request)
  #   render :json => response.body
  # end
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :products
    def self.muestralo
        response = RestClient.get'192.168.34.4:3000/stores'
        @response = JSON.parse(response)
        return @response
      end
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def index
    @admin = Product.all
  end
  
  def show
    @admin = Product.all
  end

  def new
    @admin = Product.new
  end

  def create 
    @admin = Product.new(product_params)
    if @admin.save
      redirect_to admin_path
    else
    render :new
   end
  end

  private
  
     def product_params
       params.require(:admin).permit(:name, :image, :description, :price, :quantity, :store_id)
     end
  
end

app/controllers/api/v1/admins_controller.rb
class Api::V1::AdminsController < ApplicationController
def index
@admins = Admin.all
render :json => @admins
end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
    def index 
        @products = Product.all
        render :json => @products
       end
       
       def show
       end
       
       def edit
    
       end
       
       def update
       
       end
       
       def new
        @product = Product.new
       end
       
       def create 
        @product = Product.new(product_params)
        if @product.save
          redirect_to product_path
        else
        render :new
       end
      end
       
       def destroy
       Product.find(params[:id]).delete
       render :json => Product.all
       end
    
     
    
       private
    
       def product_params
         params.require(:person).permit(:name, :image, :description, :price, :quantity, :store_id)
       end
end

app/controllers/api/v1/stores_controller.rb
class Api::V1::StoresController < ApplicationController
    
    
    def index 

        @stores = Store.all
        render :json => @stores
       end
       
       def show
       end
       
      
       
       def update
       
       end
       
       def new
        @store = Store.new
       end
       
    #    def create 
    #     @store = Store.new(product_params)
    #     if @product.save
    #       redirect_to product_path
    #     else
    #     render :new
    #    end
    #   end
       
       def destroy
       Product.find(params[:id]).delete
       render :json => Product.all
       end
    
     
    
    #    private
    
    #    def product_params
    #      params.require(:person).permit(:name, :image, :description, :price, :quantity, :store_id)
    #    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index 
    # @products = Product.muestralos
    # @products2 = Product.muestralos_2
    @products3 = Product.muestralos_3
    # @products4 = Product.muestralos_4
    # @products5 = Product.muestralos_5
    # render json: @products
    end
    def create 
        @products = Product.new(product_params)
        if @products.save
          redirect_to stores_path
        else
        render :new
       end
      end
    
      def new 
        @products = Product.new
        @products.save
      end

      def show
    @stores = Product.all
  end
    
      private
      
         def product_params
           params.permit(:name, :image, :description, :price, :quantity, :store_id)
         end
   
end

app/controllers/stores_controller.rb
class   StoresController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "secret", only: "index"

    
    def index 
     @stores = Product.all
    end

    def show
    end
    
    def destroy
     Product.find(params[:id]).delete
     redirect_to stores_path, :alert => "Watch it, mister!"
    end
       
 end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/admins/index.html.haml
%h1 Admin Login
%table{border: 2}
  %tr
    %th Name
    %th Description
    %th Price
    %th Quantity
  - @admin.each do |x|
    %tr
      %td= x['name']
      %td= x['description']
      %td= x['price']
      %td= x['quantity']
%br/

app/views/admins/new.html.haml
%h1 New Product
%br/

= form_with(model: @admin, local: true) do |form|
  
    = form.submit :hola_presiona_si_quieres_crear_un_nuevo_producto
    .field 
    = form.hidden_field :store_id

app/views/admins/show.html.haml
%h1 Admin Login
%table{border: 2}
  %tr
    %th Name
    %th Description
    %th Price
    %th Quantity
    %th Config
  - @admin.each do |x|
    %tr
      %td= x['name']
      %td= x['description']
      %td= x['price']
      %td= x['quantity']
      %td= link_to('new', new_product_path)
%br/

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyect</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://designers.hubspot.com/hs-fs/hub/327485/file-2054199286-css/font-awesome.css"En Inglés rel="stylesheet">
    <script src="https://use.fontawesome.com/b63d569465.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.haml
%body
  .background-image-store
  %main
    .sidebar
      %img#sidebar-img{:src => "assets/pictures/sidebar.gif"}/
      %img.logohack{:src => "assets/pictures/hacklogo.svg"}/
      %menu
        .options
          %i.fa.fa-home{"aria-hidden" => "true"}
          = link_to "Home", "/stores/show", :class => "nuevoproduct"
        .options
          %a Tiendas
          %i.fa.fa-shopping-bag{"aria-hidden" => "true"}
        .options
          %i.fa.fa-search{"aria-hidden" => "true"}
          = link_to "New Product", new_product_path, :class => "nuevoproduct"
        .login
          %i.fa.fa-user-circle{"aria-hidden" => "true"}
    .product
      %form
%h1.titulo1 Products
%table.tablita{border: 2}
  %tr
    %th Name
    %th Description
    %th Price
    %th Quantity
    %th Category
    %th Store
  - @products3.each do |a|
    %tr
      %td= a['name']
      %td= a['description']
      %td= a['price']
      %td= a['quantity']
      %td= a['category']
      %td= a['store']
      %tr
      %br/
= link_to('login', stores_path)
   

app/views/products/new.html.haml
%h1.supercute New Product
%form.beauty{:action => "#{products_path}", :method => "post"}
  %div
    %label{:for => "name"} Name:
    %input#name{:name => "name", :placeholder => "mamey", :type => "text"}
  %div
    %label{:for => "name"} Image:
    %input#name{:name => "image", :placeholder => "inserte url", :type => "text"}
  %div
    %label{:for => "name"} Description:
    %input#name{:name => "description", :placeholder => "Breve Descripcion", :type => "text"}
  %div
    %label{:for => "name"} Price:
    %input#name{:name => "price", :placeholder => "Inserte Precio", :type => "numeric"}
  %div
    %label{:for => "name"} Quantity:
    %input#name{:name => "quantity", :placeholder => "Inserte Cantidad ", :type => "numeric"}
  %div
    %label{:for => "store_id"}
    %input#ID{:name => "store_id",:value => "1", :hidden => "true"}
  .button
    %button.cutenes{:type => "submit"}
      %i.fa.fa-instagram.fa-lg{"aria-hidden" => "true"} Create Product
   
    

app/views/products/show.html.haml
%body
  .background-image-store
  %main
    .sidebar
      %img#sidebar-img{:src => "assets/pictures/sidebar.gif"}/
      %img.logohack{:src => "assets/pictures/hacklogo.svg"}/
      %menu
        .options
          %i.fa.fa-home{"aria-hidden" => "true"}
          = link_to "Home", "/stores/show", :class => "nuevoproduct"
        .options
          %a Tiendas
          %i.fa.fa-shopping-bag{"aria-hidden" => "true"}
        .options
          %i.fa.fa-search{"aria-hidden" => "true"}
          = link_to "New Product", new_product_path, :class => "nuevoproduct"
        .login
          %i.fa.fa-user-circle{"aria-hidden" => "true"}
    .product
      %form
%h1.titulo1 Products
%table.tablita{border: 2}
  %tr
    %th Category
    %th Store
  - @stores.each do |a|
    %tr
      %td= a['category']
      %td= a['store']
      %tr
      %br/
= link_to('login', stores_path)

app/views/stores/index.html.haml
%body
  .background-image-store
  %main
    .sidebar
      %img#sidebar-img{:src => "assets/pictures/sidebar.gif"}/
      %img.logohack{:src => "assets/pictures/hacklogo.svg"}/
      %menu
        .options
          %i.fa.fa-home{"aria-hidden" => "true"}
          = link_to "Home", "/stores/show", :class => "nuevoproduct"
        .options
          %a
          %i.fa.fa-shopping-bag{"aria-hidden" => "true"}
          = link_to "Tiendas", "/products/show", :class => "nuevoproduct"
        .options
          %i.fa.fa-search{"aria-hidden" => "true"}
          = link_to "New Product", new_product_path, :class => "nuevoproduct"
        .login
          %i.fa.fa-user-circle{"aria-hidden" => "true"}
    .product
      %form
%h1.titulo1 Hack Library
%form.button_to{:action => "/stores/1", :method => "post"}
  %input.escondido{:name => "_method", :value => "delete"}/
  %input.deleteate{"data-confirm" => "Are you sure?", :type => "submit", :value => "X"}/
%form.button_to{:action => "/stores/2", :method => "post"}
  %input.escondido{:name => "_method", :value => "delete"}/
  %input.deleteate2{"data-confirm" => "Are you sure?", :type => "submit", :value => "X"}/
%form.button_to{:action => "/stores/3", :method => "post"}
  %input.escondido{:name => "_method", :value => "delete"}/
  %input.deleteate3{"data-confirm" => "Are you sure?", :type => "submit", :value => "X"}/
%form.button_to{:action => "/stores/4", :method => "post"}
  %input.escondido{:name => "_method", :value => "delete"}/
  %input.deleteate4{"data-confirm" => "Are you sure?", :type => "submit", :value => "X"}/
%form.button_to{:action => "/stores/5", :method => "post"}
  %input.escondido{:name => "_method", :value => "delete"}/
  %input.deleteate5{"data-confirm" => "Are you sure?", :type => "submit", :value.pintate => "X"}/
%table.tablauno{border: 2}
  %tr
    %th Image
    %th Name
    %th Description
    %th Price
    %th Quantity
    %th Delete
  - @stores.each do |a|
    %tr
      %td
        =image_tag "#{a['image']}", :class => "arreglando"
      %td= a['name']
      %td= a['description']
      %td= a['price']
      %td= a['quantity']
      %tr
      %br/
= link_to('new', new_product_path)

app/views/stores/show.html.haml
%body
  .background-image
  %span.textstyle
    EL mercado virtual de HACK
    %br/
    Gran variedad, pocos productos
  %img.logohack1{:src => "/assets/pictures/hacklogo.svg"}/
  .logomarket Market
  .btn1
    = link_to "API", api_v1_products_path, :class => "api"
  .btn2
    = link_to "MARKET", products_path, :class => "markettt"
  .login
    %i.fa.fa-user-circle{"aria-hidden" => "true"}
    = link_to "Login", stores_path, :class => "login1"

:css
  body, html{
      width: 100%;
      height: 100%;
      margin:0;
    }